version: 2
defaults: &defaults
  working_directory: ~/repo
  environment:
    NODE_ENV: test
  docker:
    - image: circleci/node:14.15.1

jobs:
  setup-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH' >> $BASH_ENV
      - restore_cache:
          key: v-0-0-4-node_modules_dir-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d "node_modules" ]; then
              for i in 1 2; do
                yarn install --prefer-offline && break || sleep 15;
              done
              git checkout yarn.lock
            fi
      - save_cache:
          key: v-0-0-4-node_modules_dir-{{ checksum "yarn.lock" }}
          paths:
            - packages/project/node_modules
            - packages/quantification/node_modules
            - packages/ggit/node_modules
            - packages/errors/node_modules
            - packages/math/node_modules
            - packages/hooks/node_modules
            - packages/bento/node_modules
            - node_modules
            - ~/.cache
  run-regular-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH' >> $BASH_ENV
      - restore_cache:
          key: v-0-0-4-node_modules_dir-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests and Collect Coverage
          command: |
            cd ~/repo
            yarn run test --coverage
      - run:
          name: Upload Coverage Reports
          command: codecov --disable=gcov --token=$CODECOV_TOKEN

  run-chromatic:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v-0-0-4-node_modules_dir-{{ checksum "yarn.lock" }}
      - run:
          name: Run Chromatic
          command: |
            cd ~/repo
            cd packages/bento && yarn chromatic --debug --skip 'dependabot/**' --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes

workflows:
  version: 2
  test:
    jobs:
      - setup-tests
      - run-regular-tests:
          requires:
            - setup-tests
      - run-chromatic:
          requires:
            - setup-tests
